name: Create New Tag

on:
  pull_request:
    branches:
      - main

jobs:
  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get project version
        id: get_version
        run: echo "::set-output name=version::$(grep -oP '(?<=version = ").*(?="\s*$)' Cargo.toml)"
        
      - name: Create Tag
        uses: actions/github-script@v5
        with:
          script: |
            const version = '${{ steps.get_version.outputs.version }}';
            console.log(`Creating tag for version ${version}`);
            const tag = `v${version}`;
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            });

